"""empty message

Revision ID: 1316fba551a9
Revises: 7349ce2f6db4
Create Date: 2020-07-11 17:55:48.192865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1316fba551a9'
down_revision = '7349ce2f6db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codenames_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('front', sa.String(), nullable=True),
    sa.Column('back', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codenames_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codenames_words_variant'), ['variant'], unique=False)

    with op.batch_alter_table('codenames_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('words', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_rooms', schema=None) as batch_op:
        batch_op.drop_column('words')

    with op.batch_alter_table('codenames_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codenames_words_variant'))

    op.drop_table('codenames_words')
    # ### end Alembic commands ###
