"""empty message

Revision ID: 2269de9db019
Revises: 5298e50ab178
Create Date: 2020-07-13 17:57:54.927019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2269de9db019'
down_revision = '5298e50ab178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('words_left', sa.Integer(), nullable=True))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.drop_column('words_left')

    # ### end Alembic commands ###
