"""empty message

Revision ID: 29c3a09147a2
Revises: 770cef0401b1
Create Date: 2020-07-19 18:35:37.750619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c3a09147a2'
down_revision = '770cef0401b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_details', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_rooms', schema=None) as batch_op:
        batch_op.drop_column('state_details')

    # ### end Alembic commands ###
