"""empty message

Revision ID: 5298e50ab178
Revises: 1316fba551a9
Create Date: 2020-07-13 17:45:12.678194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5298e50ab178'
down_revision = '1316fba551a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clue', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('turns_left', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_rooms', schema=None) as batch_op:
        batch_op.drop_column('turns_left')
        batch_op.drop_column('clue')

    # ### end Alembic commands ###
