"""empty message

Revision ID: 7349ce2f6db4
Revises: 
Create Date: 2020-07-10 18:57:58.357627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7349ce2f6db4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codenames_players',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sid', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_data.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['codenames_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codenames_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=10), nullable=True),
    sa.Column('team_name', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('spymaster', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['codenames_rooms.id'], ),
    sa.ForeignKeyConstraint(['spymaster'], ['codenames_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codenames_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codenames_teams_room_id'), ['room_id'], unique=False)

    op.create_table('room_data',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('game', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('room_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_data_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_data_username'), ['username'], unique=False)

    op.create_table('codenames_rooms',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('grid', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['room_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codenames_rooms')
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_data_username'))
        batch_op.drop_index(batch_op.f('ix_user_data_room_id'))

    op.drop_table('user_data')
    op.drop_table('room_data')
    with op.batch_alter_table('codenames_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codenames_teams_room_id'))

    op.drop_table('codenames_teams')
    op.drop_table('codenames_players')
    # ### end Alembic commands ###
