"""empty message

Revision ID: 770cef0401b1
Revises: 2269de9db019
Create Date: 2020-07-19 11:17:16.676454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770cef0401b1'
down_revision = '2269de9db019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codenames_players', schema=None) as batch_op:
        batch_op.drop_column('sid')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('sid')

    with op.batch_alter_table('codenames_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.VARCHAR(length=36), nullable=True))

    # ### end Alembic commands ###
